apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: observability
data:
  config.alloy: |
    prometheus.exporter.gcp "infra" {
      project_ids      = ["bens-project-462804"]
      metrics_prefixes = [
        "loadbalancing.googleapis.com",
        "pubsub.googleapis.com",
        "compute.googleapis.com/instance",
        "artifactregistry.googleapis.com",
      ]
      ingest_delay            = true
      drop_delegated_projects = true
    }

    prometheus.scrape "gcp" {
      targets         = prometheus.exporter.gcp.infra.targets
      forward_to      = [prometheus.remote_write.grafana_cloud.receiver]
      scrape_interval = "5m"
    }

    prometheus.remote_write "grafana_cloud" {
      endpoint {
        url = sys.env("GRAFANA_CLOUD_PROMETHEUS_URL")
        basic_auth {
          username = sys.env("GRAFANA_CLOUD_PROMETHEUS_USER")
          password = sys.env("GRAFANA_CLOUD_PROMETHEUS_PASSWORD")
        }
      }
    }
