apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-exporter
  namespace: apps
  annotations:
    iam.gke.io/gcp-service-account: billing-exporter@bens-project-462804.iam.gserviceaccount.com
